export const reducerCases = {
     SET_USER: "SET_USER",
     SET_TOKEN: "SET_TOKEN",
     SET_SEARCH: "SET_SEARCH",
     SET_PLAYER: "SET_PLAYER",
     SET_DEVICE: "SET_DEVICE",
     SET_PLAYING: "SET_PLAYING",
     SET_PLAYLIST: "SET_PLAYLIST",
     SET_PLAYLISTS: "SET_PLAYLISTS",
     SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
     SET_PLAYER_STATE: "SET_PLAYER_STATE",
     SET_DATA: "SET_DATA",
};
   